### ISSUE TITLE
Proxy is not working. errorCode: ERR_NO_SUPPORTED_PROXIES

### ISSUE THREAD

**Issue by 7jrxt42BxFZo4iAnN4CX** [spider-rs/spider#289]
Tried HTTPS and SOCKS5 proxy, both did not work.

**Cargo.toml:**
```toml
spider_chrome = {git = "https://github.com/spider-rs/spider.git"}
spider = { git = "https://github.com/spider-rs/spider.git", 
           features = ["chrome", "ua_generator", "socks", "chrome_stealth", "real_browser", "headers"]}
```

**Code:**
```rust
  let proxy_ip = "1.2.3.4";
  let url = "https://showip.net/".to_string();

  //- ─── Reqwest ──────────────────────────────────────────────
  let client = ClientBuilder::new()
    .proxy(reqwest::Proxy::all(my_proxy.url()).unwrap())
    .https_only(true)
    .build()
    .map_err(|error| SharedError::ReqwestBuilderError { error }).unwrap();

  let html = client
    .get(url.as_str())
    .send()
    .await
    .unwrap()
    .text()
    .await
    .unwrap();

  println!("Reqwest: {}", html.contains(proxy_ip));

  //- ─── spider ──────────────────────────────────────────────
  let mut website = Website::new(&url)
    .with_limit(1)
    .with_proxies(Some(vec![my_proxy.url()]))
    .with_redirect_limit(2)
    .with_retry(2)
    .build()
    .unwrap();

  website.scrape().await; // OR  website.crawl().await;

  for page in website.get_pages().unwrap().iter() {
    println!("get_url_final: {}, get_html.len:{}", page.get_url_final(), page.get_html().len(),);
    println!("Spider: {}", page.get_html().contains(proxy_ip));
  }

```

**Output:**
>Reqwest: true
get_url_final: chrome-error://chromewebdata/, get_html.len:177378
Spider: false

**page.get_html().contains:**
>..."errorCode\":\"ERR_NO_SUPPORTED_PROXIES\" .... "This site can’t be reached\" ...."The webpage at \\u003Cstrong>https://showip.net/\\u003C/strong> might be temporarily down or it may have moved permanently to a new web address.\"
